name: System Check

on:
  push:
    branches:
      - main

jobs:
  system-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        security-checks: 'vuln,config,secret'
        hide-progress: false

    - name: Run system check script
      run: |
        python3 system_check.py

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: system-check-report
        path: reports/
